baseURL = "http://sudhanshu55.github.io/"
languageCode = "en-us"
title = "Sudhanshu's Page"
theme="codex"
disqusShortname="sudhanshu55-github-io"

[params]
  #github = "https://github.com/mridulganga"
  #gitlab = "https://gitlab.com/mridulganga"
  #instagram = "https://www.instagram.com/mridulkepler"
  #linkedin = "https://www.linkedin.com/in/mridul-ganga-03326aa2"
  #telegram = "https://t.me/mridulganga"
  iconOrder = ["Gitlab", "GitHub", "Instagram", "Linkedin", "Telegram"]
  showPageTitleInTOC = true


[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true


# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "sudhanshu"
  title = "SudhanshuSharma"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
